---
title: "presentation transcript"
output:
  word_document: default
  html_document: default
---


Good morning everyone, I am glad to be here to present our findings regarding food choices at different timing among UK adults. 

It has been shown that the timing of energy and carbohydrate intake is associated with obesity and diabetes. Our aim was to look at the relationships between food groups and the time they were eaten, and how such associations may vary by diabetes status.

The data was from the UK National Diet and Nutrition Survey, nearly 7000 adults were included in our anlaysis. Altogether, we had about 750,000 food recordings collected with a 4-day food diary.

We used correspondence analysis as a tool for data mining, visualisation and hypotheses generation. Biplots that graphically showing the association between time of day and food groups were derived for all adults and seprately according to their diabetes status. 

The definitions of diabetes and numbers of subjects are shown in Table 1. 

Afterwards, logistic regression models with generalised estimating equation that account for repeated measurements were used to test hypotheses generated by correspondence analysis, comparing the odds of being consumed later at night to earlier time in the day. 

These figures here show the potential associations between time and food groups by the defined diabetes status. 

Correspondence analysis allows us to plot both the points of time and food in the same figure where here we see later time are in the upper side of the graph. And when food and time points are close together and away from the origin then it is suggested that there is an association. 


<!-- The vertical axis here indicates the time from earlier (at the bottom) to later than 8 pm at night (at the top) in each graph.  -->

Therefore, in the graph, food appears close to the time, means they were consumed at that time.

We colored those food for further hypotheses testing in red as they are considered to be relatively unhealthy and possibly being consumed differently by diabetes status in terms of the timing. For example, sugar confectionery, regular soft drinks, chocolates and etc. appear much further at the top of the figures among non diagnosed diabetes patients compared to the other participants. 

The results from testing these hypotheses are listed in table 2. Apparently, all chosen unhealthy foods had higher odds of being consumed between 8pm to 6am than ealier time. Especially, for people with undiagnosed diabetes, they had 12 times higher odds of eating sugar confectionery, and nearly 2 times higher odds of drinking sweetened soft drink during the night time than earlier time, whereas the associations were weaker among the the other participants. 

In conclusion, highly processed and easily accessible foods and drinks are more likely to be consumed in the evening. Un-diagnosed diabetes patients are likely to be caused as they chose to have a number of less healthy foods at night. 

Thanks for listening and I am happy to take any quesitions. 

